### ISSUE TITLE
Version identification error

### ISSUE THREAD

**Issue by Tellik** [al132mc/A-Lib#2] opened 2022-11-02 22:06 UTC
AlchemyLib - 1.19.2, both 1.0.15 and 1.0.16 are identified on Curseforge as being for MC version 1.18.2. This is leading to incorrect installations through the GD Launcher (probably Curseforge client as well), since they are configured to grab the latest version for the MC version installed.

Identified as supporting version 1.18.2:

https://www.curseforge.com/minecraft/mc-mods/alchemylib/files/4060712
https://www.curseforge.com/minecraft/mc-mods/alchemylib/files/4060625

**Comment by Dark-Arcana** [comment] 2022-11-02 22:09
Sounds like an issue with GDLauncher grabbing the latest version rather than a specific version. Though, this is also an issue on my part because I didn't specify which version should be done. I wasn't planning on anyone using it yet as I marked it a beta. Future versions will have more polish and not have issues like this. So I'm going to close this, but it is duly noted and will be worked on!

**Closed as completed by Dark-Arcana** 2022-11-02 22:09 UTC

**Comment by Tellik** [comment] 2022-11-02 22:16
The curseforge site at the very least also identify them as being for version 1.18.2 under supported versions (specific file linked previous), and on the main page on the sidebar. Just wanted to give you a heads up since it'll probably cause more confusion than just for me in the future.

![image](https://user-images.githubusercontent.com/6219444/199612796-33bbea27-6abd-40e8-aaac-f5b979118e14.png)

**Comment by Dark-Arcana** [comment] 2022-11-02 22:16
Oh I know what the issue is. I just made a mistake when I published it. So it won't be an issue in the next version is all.

**Comment by Dark-Arcana** [comment] 2022-11-03 02:19
Just want to let you know I pushed an update and this is fixed!
